"""Generate stable APWorld and client identity tables from the canonical catalog."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def pascal(display_name: str) -> str:
    result = "".join(part[:1].upper() + part[1:] for part in re.findall(r"[A-Za-z0-9]+", display_name))
    return "Plus" + result if result[:1].isdigit() else result


def csharp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


EQUIPMENT_REWARD_GROUPS = {
    "toolsanity": ("reward_tools", 8410000),
    "weaponsanity": ("reward_weapons", 8411000),
    "jewelrysanity": ("reward_jewelry", 8412000),
    "accessanity": ("reward_accessories", 8413000),
    "armorsanity": ("reward_armor", 8414000),
}


def equipment_rewards(catalog: dict) -> list[dict]:
    objects = {record["key"]: record for record in catalog["objects"]}
    offsets = {group: 0 for group in EQUIPMENT_REWARD_GROUPS}
    result = []
    for check in catalog["checks"]:
        group = check["group"]
        if group not in EQUIPMENT_REWARD_GROUPS:
            continue
        option, base = EQUIPMENT_REWARD_GROUPS[group]
        target = objects[check["trigger"]["target_key"]]
        name = check["display_name"].removeprefix("Collect ")
        result.append({
            "name": name,
            "id": base + offsets[group],
            "option": option,
            "internal_name": target["internal_name"],
        })
        offsets[group] += 1
    names = [record["name"] for record in result]
    if len(names) != len(set(names)):
        raise ValueError("Equipment reward names must be unique")
    return result


def render_locations(catalog: dict) -> str:
    rows = "\n".join(
        f"    {json.dumps(record['display_name'], ensure_ascii=False)}: {record['stable_id']},"
        for record in catalog["checks"]
    )
    metadata = "\n".join(
        f"    {json.dumps(record['display_name'], ensure_ascii=False)}: "
        f"({json.dumps(record['group'])}, {json.dumps(record['goal_scope'])}, "
        f"{repr(tuple(record['normal']['all_of']))}),"
        for record in catalog["checks"]
    )
    return f'''# Generated by tools/generate_catalog_consumers.py. Do not edit by hand.
from BaseClasses import Location


LOCATION_NAME_TO_ID = {{
{rows}
}}

LOCATION_METADATA = {{
{metadata}
}}


class CoreKeeperLocation(Location):
    game = "Core Keeper"
'''


def render_items(catalog: dict, cache_policy: dict, license_policy: dict) -> str:
    equipment = equipment_rewards(catalog)
    ids = "\n".join(
        f"    {json.dumps(record['display_name'], ensure_ascii=False)}: {record['stable_id']},"
        for record in catalog["rewards"]
    ) + "\n" + "\n".join(f"    {json.dumps(row['name'])}: {row['id']}," for row in equipment)
    classification_names = {
        "filler": "ItemClassification.filler",
        "useful": "ItemClassification.useful",
        "progression": "ItemClassification.progression",
        "progression_useful": "ItemClassification.progression | ItemClassification.useful",
    }
    classifications = "\n".join(
        f"    {json.dumps(record['display_name'], ensure_ascii=False)}: {classification_names[record['classification']]},"
        for record in catalog["rewards"]
    ) + "\n" + "\n".join(f"    {json.dumps(row['name'])}: ItemClassification.filler," for row in equipment)
    names = "\n".join(
        f"        {json.dumps(record['display_name'], ensure_ascii=False)},"
        for record in catalog["rewards"]
    )
    cache_weights = "\n".join(
        f'        ({json.dumps(cache["item_name"])}, int(world.options.{cache["key"]}_weight)),'
        for cache in cache_policy["caches"]
    )
    skill_point_names = [
        reward["display_name"]
        for reward in catalog["rewards"]
        if reward["delivery"]["kind"] == "skill_points"
    ]
    skill_point_rows = "\n".join(
        f'        names.extend([{json.dumps(name)}] * 5)'
        for name in skill_point_names
    )
    equipment_rows = "\n".join(
        f'    if world.options.{option}:\n        filler_candidates.extend({json.dumps([row["name"] for row in equipment if row["option"] == option])})'
        for option, _ in EQUIPMENT_REWARD_GROUPS.values()
    )
    return f'''# Generated by tools/generate_catalog_consumers.py. Do not edit by hand.
from __future__ import annotations

from typing import TYPE_CHECKING

from BaseClasses import Item, ItemClassification
from Options import OptionError

from .options import LICENSE_OPTIONS

if TYPE_CHECKING:
    from .world import CoreKeeperWorld


ITEM_NAME_TO_ID = {{
{ids}
}}

ITEM_CLASSIFICATIONS = {{
{classifications}
}}


class CoreKeeperItem(Item):
    game = "Core Keeper"


def create_item(world: CoreKeeperWorld, name: str) -> CoreKeeperItem:
    return CoreKeeperItem(name, ITEM_CLASSIFICATIONS[name], ITEM_NAME_TO_ID[name], world.player)


def create_items(world: CoreKeeperWorld) -> None:
    location_count = len(world.multiworld.get_unfilled_locations(world.player))
    names = []
    for item_name, option_name, copies in LICENSE_OPTIONS:
        if getattr(world.options, option_name):
            names.extend([item_name] * copies)
    if world.options.skill_points:
{skill_point_rows}
    legendary_options = [
        ("soul_seeker_cache", "Soul Seeker Cache"),
        ("titan_breath_cache", "Titan Breath Cache"),
        ("phantom_spark_cache", "Phantom Spark Cache"),
        ("rune_song_cache", "Rune Song Cache"),
        ("credence_of_ruin_cache", "Credence of Ruin Cache"),
        ("stormbringer_cache", "Stormbringer Cache"),
    ]
    names.extend(name for option, name in legendary_options if getattr(world.options, option))
    if len(names) > location_count:
        raise OptionError(
            "The selected license and Skill Points rewards require "
            f"{{len(names)}} locations, but only {{location_count}} are enabled. "
            "Enable more checks, disable some license rewards, or disable Skill Points."
        )
    cache_weights = [
{cache_weights}
        ("Empty Cache", int(world.options.empty_cache_weight)),
    ]
    cache_weights = [(name, weight) for name, weight in cache_weights if weight > 0]
    total_weight = sum(weight for _, weight in cache_weights)
    filler_slots = location_count - len(names)
    filler_candidates = []
{equipment_rows}
    while len(filler_candidates) < filler_slots:
        if not total_weight:
            filler_candidates.append(world.get_filler_item_name())
            continue
        roll = world.random.randrange(total_weight)
        for cache_name, weight in cache_weights:
            if roll < weight:
                filler_candidates.append(cache_name)
                break
            roll -= weight
    # Equipment candidates are in the approved prototype progression order.
    # Select the prefix before randomizing placement so a constrained pool
    # removes later equipment first instead of cutting arbitrary entries.
    selected_fillers = filler_candidates[:filler_slots]
    world.random.shuffle(selected_fillers)
    names.extend(selected_fillers)
    world.allow_priority_overflow(names)
    if world.options.early_repair_and_salvage and world.options.repair_salvage_license:
        world.multiworld.local_early_items[world.player]["Salvage and Repair Station License"] = 1
        if world.options.furnace_license:
            world.multiworld.local_early_items[world.player]["Progressive Furnace License"] = 1
    world.multiworld.itempool += [world.create_item(name) for name in names]
'''


def render_location_ids(catalog: dict) -> str:
    constants = "\n".join(
        f"    public const long {pascal(record['key'])} = {record['stable_id']};"
        for record in catalog["checks"]
    )
    names = "\n".join(
        f"            {pascal(record['key'])} => {csharp_string(record['display_name'])},"
        for record in catalog["checks"]
    )
    return f'''// Generated by tools/generate_catalog_consumers.py. Do not edit by hand.
namespace CoreKeeperArchipelago.Mainline;

internal static class LocationIds
{{
{constants}

    public static string GetName(long locationId)
        => locationId switch
        {{
{names}
            _ => "Unknown location " + locationId.ToString(System.Globalization.CultureInfo.InvariantCulture)
        }};
}}
'''


def render_item_ids(catalog: dict) -> str:
    constants = "\n".join(
        f"    public const long {pascal(record['display_name'])} = {record['stable_id']};"
        for record in catalog["rewards"]
    ) + "\n" + "\n".join(
        f"    public const long {pascal(record['name'])} = {record['id']};"
        for record in equipment_rewards(catalog)
    )
    return f'''// Generated by tools/generate_catalog_consumers.py. Do not edit by hand.
namespace CoreKeeperArchipelago.Mainline;

internal static class ItemIds
{{
{constants}
}}
'''


def render_object_reward_policy(catalog: dict) -> str:
    rows = "\n".join(
        f"            case {record['id']}: objectId = ObjectID.{record['internal_name']}; return true;"
        for record in equipment_rewards(catalog)
    )
    return f'''// Generated by tools/generate_catalog_consumers.py. Do not edit by hand.
namespace CoreKeeperArchipelago.Mainline;

internal static class ObjectRewardPolicy
{{
    internal static bool TryGet(long itemId, out ObjectID objectId)
    {{
        switch (itemId)
        {{
{rows}
        }}
        objectId = ObjectID.None;
        return false;
    }}
}}
'''


def render_check_targets(catalog: dict) -> str:
    objects = {record["key"]: record for record in catalog["objects"]}
    natural: dict[int, list[int]] = {}
    kills: dict[tuple[int, int], list[int]] = {}
    dynamic_kills: dict[int, list[int]] = {}
    interactions: dict[int, list[int]] = {}
    for check in catalog["checks"]:
        trigger = check["trigger"]
        if trigger["kind"] not in ("natural_acquisition", "kill", "interact"):
            continue
        target = objects[trigger["target_key"]]
        if trigger["kind"] == "natural_acquisition":
            natural.setdefault(target["object_id"], []).append(check["stable_id"])
        elif trigger["kind"] == "kill":
            if check["group"] == "cattle_mutilation":
                dynamic_kills.setdefault(target["object_id"], []).append(check["stable_id"])
            else:
                kills.setdefault((target["object_id"], int(target.get("variation", 0))), []).append(check["stable_id"])
        else:
            interactions.setdefault(target["object_id"], []).append(check["stable_id"])

    def rows(kind: str) -> str:
        return "\n".join(
            "        { ObjectID.%s, new long[] { %s } },"
            % (objects[next(check["trigger"]["target_key"] for check in catalog["checks"]
                            if check["stable_id"] == ids[0])]["internal_name"], ", ".join(map(str, ids)))
            for object_id, ids in sorted(natural.items())
        )

    def kill_rows() -> str:
        return "\n".join(
            "        { (ObjectID.%s, %d), new long[] { %s } },"
            % (objects[next(check["trigger"]["target_key"] for check in catalog["checks"]
                            if check["stable_id"] == ids[0])]["internal_name"], variation, ", ".join(map(str, ids)))
            for (object_id, variation), ids in sorted(kills.items())
        )

    def interaction_rows() -> str:
        return "\n".join(
            "        { ObjectID.%s, new long[] { %s } },"
            % (objects[next(check["trigger"]["target_key"] for check in catalog["checks"]
                            if check["stable_id"] == ids[0])]["internal_name"], ", ".join(map(str, ids)))
            for object_id, ids in sorted(interactions.items())
        )

    def dynamic_kill_rows() -> str:
        return "\n".join(
            "        { ObjectID.%s, new long[] { %s } },"
            % (objects[next(check["trigger"]["target_key"] for check in catalog["checks"]
                            if check["stable_id"] == ids[0])]["internal_name"], ", ".join(map(str, ids)))
            for object_id, ids in sorted(dynamic_kills.items())
        )

    return f'''// Generated by tools/generate_catalog_consumers.py. Do not edit by hand.
using System;
using System.Collections.Generic;

namespace CoreKeeperArchipelago.Mainline;

internal static class CheckTargets
{{
    private static readonly IReadOnlyDictionary<ObjectID, long[]> Natural =
        new Dictionary<ObjectID, long[]>
        {{
{rows("natural_acquisition")}
        }};

    private static readonly IReadOnlyDictionary<(ObjectID, int), long[]> Kills =
        new Dictionary<(ObjectID, int), long[]>
        {{
{kill_rows()}
        }};

    private static readonly IReadOnlyDictionary<ObjectID, long[]> DynamicVariationKills =
        new Dictionary<ObjectID, long[]>
        {{
{dynamic_kill_rows()}
        }};

    private static readonly IReadOnlyDictionary<ObjectID, long[]> Interactions =
        new Dictionary<ObjectID, long[]>
        {{
{interaction_rows()}
        }};

    internal static IEnumerable<ObjectID> NaturalObjectIds => Natural.Keys;
    internal static bool IsNaturalTarget(ObjectID objectId) => Natural.ContainsKey(objectId);
    internal static IReadOnlyList<long> NaturalLocations(ObjectID objectId)
        => Natural.TryGetValue(objectId, out long[]? locations) ? locations : Array.Empty<long>();
    internal static IReadOnlyList<long> KillLocations(ObjectID objectId, int variation)
        => Kills.TryGetValue((objectId, variation), out long[]? exactLocations)
            ? exactLocations
            : DynamicVariationKills.TryGetValue(objectId, out long[]? dynamicLocations)
                ? dynamicLocations
                : Array.Empty<long>();
    internal static IReadOnlyList<long> InteractionLocations(ObjectID objectId)
        => Interactions.TryGetValue(objectId, out long[]? locations) ? locations : Array.Empty<long>();
}}
'''


def render_skill_check_targets(catalog: dict) -> str:
    rows = []
    for check in catalog["checks"]:
        trigger = check["trigger"]
        if trigger["kind"] != "skill_level":
            continue
        skill, level = trigger["target_key"].rsplit("_", 1)
        rows.append(
            f"        new SkillCheckTarget(SkillID.{pascal(skill)}, {int(level)}, {check['stable_id']}),"
        )
    return f'''// Generated by tools/generate_catalog_consumers.py. Do not edit by hand.
namespace CoreKeeperArchipelago.Mainline;

internal readonly struct SkillCheckTarget
{{
    internal SkillCheckTarget(SkillID skill, int level, long locationId)
    {{
        Skill = skill;
        Level = level;
        LocationId = locationId;
    }}

    internal SkillID Skill {{ get; }}
    internal int Level {{ get; }}
    internal long LocationId {{ get; }}
}}

internal static class SkillCheckTargets
{{
    internal static readonly SkillCheckTarget[] All =
    {{
{chr(10).join(rows)}
    }};
}}
'''


def render_reward_cache_pools(policy: dict) -> str:
    blocks = []
    for cache in policy["caches"]:
        name = pascal(cache["key"])
        if "choices" in cache:
            objects = "\n".join(
                f"        ObjectID.{choice['object']}," for choice in cache["choices"]
            )
            amounts = "\n".join(
                f"        {choice['amount']}," for choice in cache["choices"]
            )
            blocks.append(
                f"    internal static readonly ObjectID[] {name}Objects =\n"
                f"    {{\n{objects}\n    }};\n"
                f"    internal static readonly int[] {name}Amounts =\n"
                f"    {{\n{amounts}\n    }};"
            )
            continue
        objects = "\n".join(f"        ObjectID.{value}," for value in cache["objects"])
        blocks.append(
            f"    internal const int {name}Minimum = {cache['minimum_amount']};\n"
            f"    internal const int {name}Maximum = {cache['maximum_amount']};\n"
            f"    internal const int {name}Step = {cache.get('amount_step', 1)};\n"
            f"    internal static readonly ObjectID[] {name} =\n"
            f"    {{\n{objects}\n    }};"
        )
    return f'''// Generated by tools/generate_catalog_consumers.py. Do not edit by hand.
namespace CoreKeeperArchipelago.Mainline;

internal static class RewardCachePools
{{
{chr(10).join(blocks)}
}}
'''


def render_reward_content_names(catalog: dict, policy: dict) -> str:
    wanted = {
        value
        for cache in policy["caches"]
        for value in (
            [choice["object"] for choice in cache.get("choices", [])]
            if "choices" in cache else cache.get("objects", [])
        )
    }
    wanted.update({
        "LegendarySword", "LightningGun", "LegendaryBow",
        "LegendaryMortar", "LegendaryStaff", "LegendaryMiningPick",
    })
    by_internal = {row["internal_name"]: row["display_name"] for row in catalog["objects"]}
    by_internal.update({
        "LegendarySword": "Rune Song",
        "LightningGun": "Storm Bringer",
        "LegendaryBow": "Phantom Spark",
        "LegendaryMortar": "Credence of Ruin",
        "LegendaryStaff": "Titan Breath",
        "LegendaryMiningPick": "Soul Seeker",
    })
    def display_name(internal_name: str) -> str:
        return by_internal.get(
            internal_name,
            re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", internal_name),
        )
    rows = "\n".join(
        f"            case ObjectID.{name}: return {csharp_string(display_name(name))};"
        for name in sorted(wanted)
    )
    return f'''// Generated by tools/generate_catalog_consumers.py. Do not edit by hand.
namespace CoreKeeperArchipelago.Mainline;

internal static class RewardContentNames
{{
    internal static string Get(ObjectID objectId)
    {{
        switch (objectId)
        {{
{rows}
            default: return objectId.ToString();
        }}
    }}
}}
'''


def render_license_access_policy(policy: dict) -> str:
    rows = []
    for station in policy["stations"]:
        if station["license"] is None:
            continue
        rows.extend((
            f"            case ObjectID.{station['internal_name']}:",
            f"                license = {csharp_string(station['license'])};",
            f"                stage = {station['stage']};",
            "                return true;",
        ))
    return f'''// Generated by tools/generate_catalog_consumers.py. Do not edit by hand.
namespace CoreKeeperArchipelago.Mainline;

internal static class LicenseAccessPolicy
{{
    internal static bool TryGetRequirement(
        ObjectID craftingTier,
        out string license,
        out int stage)
    {{
        switch (craftingTier)
        {{
{chr(10).join(rows)}
        }}
        license = string.Empty;
        stage = 0;
        return false;
    }}
}}
'''


def render_license_reward_policy(catalog: dict, policy: dict) -> str:
    reward_ids = {reward["display_name"]: reward["stable_id"] for reward in catalog["rewards"]}
    maximums: dict[str, int] = {}
    for station in policy["stations"]:
        if station["license"] is not None:
            maximums[station["license"]] = max(
                maximums.get(station["license"], 0), station["stage"]
            )
    rows = []
    for license_name, maximum in maximums.items():
        if license_name not in reward_ids:
            continue
        rows.extend((
            f"            case {reward_ids[license_name]}:",
            f"                license = {csharp_string(license_name)};",
            f"                maximum = {maximum};",
            "                return true;",
        ))
    return f'''// Generated by tools/generate_catalog_consumers.py. Do not edit by hand.
namespace CoreKeeperArchipelago.Mainline;

internal static class LicenseRewardPolicy
{{
    internal static bool TryGet(long itemId, out string license, out int maximum)
    {{
        switch (itemId)
        {{
{chr(10).join(rows)}
        }}
        license = string.Empty;
        maximum = 0;
        return false;
    }}
}}
'''


def generate(root: Path, check: bool) -> None:
    catalog = json.loads((root / "data" / "canonical_catalog.json").read_text(encoding="utf-8"))
    cache_policy = json.loads((root / "data" / "reward_cache_policy.json").read_text(encoding="utf-8"))
    license_policy = json.loads((root / "data" / "license_policy.json").read_text(encoding="utf-8"))
    outputs = {
        root / "apworld" / "core_keeper" / "locations.py": render_locations(catalog),
        root / "apworld" / "core_keeper" / "items.py": render_items(catalog, cache_policy, license_policy),
        root / "client" / "LocationIds.cs": render_location_ids(catalog),
        root / "client" / "ItemIds.cs": render_item_ids(catalog),
        root / "client" / "ObjectRewardPolicy.cs": render_object_reward_policy(catalog),
        root / "client" / "CheckTargets.cs": render_check_targets(catalog),
        root / "client" / "SkillCheckTargets.cs": render_skill_check_targets(catalog),
        root / "client" / "RewardCachePools.cs": render_reward_cache_pools(cache_policy),
        root / "client" / "RewardContentNames.cs": render_reward_content_names(catalog, cache_policy),
        root / "client" / "Runtime" / "LicenseAccessPolicy.cs": render_license_access_policy(license_policy),
        root / "client" / "LicenseRewardPolicy.cs": render_license_reward_policy(catalog, license_policy),
    }
    stale: list[str] = []
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8-sig") != content:
                stale.append(path.relative_to(root).as_posix())
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Stale generated catalog consumers: " + ", ".join(stale))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("root", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generate(args.root, args.check)


if __name__ == "__main__":
    main()
